<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NexusOS.DAL\NexusOS.DAL.csproj" />
    <ProjectReference Include="..\NexusOS.MB\NexusOS.MB.csproj" />
    <ProjectReference Include="..\NexusOS.Util\NexusOS.Util.csproj" />
  </ItemGroup>

</Project>
